version: "3"
services:
  database:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  node:
    image: node:16.3.0-buster
    command: "./node_modules/nodemon/bin/nodemon.js server"
    working_dir: /var/www
    ports:
      - 3000:3000
    volumes:
      - ./:/var/www

volumes:
  mongo-data:
    driver: local
